# Generated by Django 4.2.3 on 2023-07-17 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=64)),
                ('lieu', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=64)),
                ('desciption', models.CharField(max_length=64)),
                ('prix', models.IntegerField()),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='sama_stock.boutique')),
            ],
        ),
    ]
