# Generated by Django 4.2.3 on 2023-07-19 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sama_stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=64)),
                ('produits', models.ManyToManyField(blank=True, related_name='clients', to='sama_stock.produit')),
            ],
        ),
    ]
