name: Testing
on: push

jobs:
  test_projects:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Django
        run: |
          pip3 install --user django

      - name: Run Django unit tests
        run: |
          python3 manage.py test
