name: Testing
on: push


jobs:
    test_projects:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Run Django unit tests
          run:
            pip3 intall --user django
            pyhton3 manage.py test
